### ISSUE TITLE
Slurm support

### ISSUE THREAD

**Issue by rdwrt** [dgruber/drmaa2os#1]
This project looks interesting! Is Slurm included in the supported platforms?

**Comment by dgruber** [comment]
Sorry for the late answer. Currently not but you could integrate it if you have a litte time...

**Comment by alansill** [comment]
Easier way would be to update slurm to support DRMAA2.

**Comment by dgruber** [comment]
"PSNC DRMAA for Slurm Workload Manager (Slurm) is an implementation of Open Grid Forum DRMAA 1.0"

The JobSession functionality could be made available by using DRMAA1...so the job tracker could be implemented by using the Go DRMAA1 C wrapper.

**Comment by alansill** [comment]
How hard to make that slurm adapter work with drmaa2os? (I'd be willing to try on a test cluster, for example, along with other test setups for k8s, UGE, etc.)

**Comment by alansill** [comment]
Two new REST API efforts that may be of interest for slurm (though I hate to see peopel re-learning the need for APIs the hard way ("ontogeny recapitulates phylogeny")!

https://slurm.schedmd.com/SLUG19/REST_API.pdf
https://github.com/edf-hpc/slurm-web

**Comment by dgruber** [comment]
Thanks for the pointers, Alan.

Did you have the chance to look slurm implementation based on command line wrappers I did a year ago?

https://github.com/dgruber/drmaa2os/tree/master/pkg/jobtracker/slurmcli

**Comment by dgruber** [comment]
Hi Alan,

You can also use drmaa2os with libdrmaa for SLURM. Closing the issue now as there are two ways possible using it with SLURM. 

Here is an container image which has SLURM, compiles libdrmaa.so, and installs go and the drmaa2os package.

https://github.com/dgruber/drmaa2os/tree/master/Dockerfiles/slurm

Cheers

Daniel
